[package]
name = "dolan"
version = "0.1.0"
authors = ["Thomas McNiven <hello@trmcnvn.dev>"]
edition = "2021"

[dependencies]
pretty_env_logger = "0.5"
log = "0.4"
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
select = "0.6"
tokio = { version = "1.32", features = ["macros", "net", "rt-multi-thread"] }
axum = "0.7"
urlencoding = "2.1"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "framework",
    "rustls_backend",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
]
version = "0.12"
