# Name of your application. Used to uniquely configure containers.
service: dolan

# Name of the container image.
image: trmcnvn/dolan

# Deploy to these servers.
servers:
  - <%= ENV["MRSK_SERVER"] %>

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: trmcnvn
  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  multiarch: false
  cache:
    type: gha

# Inject ENV variables into containers
env:
  clear:
    DOLAN_DEBUG: true
    PORT: 10000
  secret:
    - DOLAN_TOKEN
    - DOLAN_OPENAI

# Configure custom arguments for Traefik
traefik:
  host_port: 80

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /healthz
  port: 10000
  max_attempts: 20
