# Name of your application. Used to uniquely configure containers.
service: dolan
minimum_version: 2.0.0

# Name of the container image.
image: dolan

# Deploy to the exe.dev VM.
servers:
  - dolan.exe.xyz

# Use a temporary local registry while deploying over SSH.
registry:
  server: localhost:5555

# Configure builder setup.
builder:
  arch: amd64
  local: true
  context: .

# Inject ENV variables into containers
env:
  clear:
    DOLAN_DEBUG: true
    PORT: 10000
  secret:
    - DOLAN_TOKEN

# Route traffic to the application's health-check server.
proxy:
  app_port: 10000
  healthcheck:
    path: /healthz

ssh:
  user: exedev
