on:
  push:
    branches:
      - master
  pull_request:

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      # make sure all code has been formatted with rustfmt
      - name: check rustfmt
        run: cargo fmt -- --check --color always
      # run clippy to verify we have no warnings
      - name: cargo fetch
        run: cargo fetch
      - name: cargo clippy
        run: cargo clippy -- -D warnings
  build:
    name: Build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [build]
    env:
      MRSK_SERVER: ${{ secrets.MRSK_SERVER }}
      DOLAN_TOKEN: ${{ secrets.DOLAN_TOKEN }}
      DOLAN_OPENAI: ${{ secrets.DOLAN_OPENAI }}
      MRSK_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
      - uses: amirmarmul/mrsk-deploy-action@v1.0.4
        with:
          args: setup
