on:
  push:
    branches:
      - master
  pull_request:

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      # make sure all code has been formatted with rustfmt
      - name: check rustfmt
        run: cargo fmt -- --check --color always
      # run clippy to verify we have no warnings
      - name: cargo fetch
        run: cargo fetch
      - name: cargo clippy
        run: cargo clippy -- -D warnings
  deploy:
    name: Deploy
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      MRSK_SERVER: ${{ secrets.MRSK_SERVER }}
      DOLAN_TOKEN: ${{ secrets.DOLAN_TOKEN }}
      DOLAN_OPENAI: ${{ secrets.DOLAN_OPENAI }}
      DOLAN_CF_ACCOUJT: ${{ secrets.DOLAN_CF_ACCOUNT }}
      DOLAN_CF_API: ${{ secrets.DOLAN_CF_API }}
      MRSK_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: false
      - uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
      - run: gem install mrsk
      - run: mrsk setup
